---
title: "R Notebook"
output: html_notebook
---

##

```{r}
library(dplyr)
library(here)
library(ggplot2)
library(lubridate)
library(data.table)
library(ggrepel)
load(here("data", "results.RData"))
```


```{r}
temp <- read.table(here("data", "predatory_journals.txt"), sep="\t", header=FALSE)

predj <- tibble(
    journal1 = gsub("\\s*\\([^\\)]+\\)","",as.character(temp$V1)) %>% tolower(),
    key1=1:length(journal1)
)

mrj <- subset(abstracts, !duplicated(journal), select=c(journal)) %>% mutate(key2=1:length(journal), journal=gsub("\\s*\\([^\\)]+\\)","",as.character(journal)) %>% tolower())

library(fedmatch)

temp <- merge_plus(data1 = mrj, data2 = predj, by.x="journal", by.y="journal1", match_type="fuzzy", unique_key_1="key2", unique_key_2="key1")

head(temp)
dim(temp$matches)



mrj$predatory <- mrj$journal %in% temp$matches$journal
table(mrj$predatory)
abstracts$journal <- gsub("\\s*\\([^\\)]+\\)","",as.character(abstracts$journal)) %>% tolower()
abstracts$predatory <- abstracts$journal %in% temp$matches$journal

group_by(abstracts, year=year(pub_date)) %>%
    summarise(n=n(), npred=sum(predatory)) %>%
    mutate(prop=npred/n, sem = sqrt(npred * (n-npred)/n^3), lci = pmax(0, prop - (1.96 * sem)), uci = pmin(prop + (1.96 * sem), 1)) %>%
    ggplot(., aes(x=year, y=prop, ymin=lci, ymax=uci)) + geom_line() + geom_ribbon(alpha=0.2) + theme(legend.position="bottom") + xlim(2005,2024) +
    geom_text(aes(label=npred), vjust=-1) +
    scale_x_continuous(breaks=seq(2005,2024,1), limits=c(2005, 2024)) +
    theme(axis.text.x=element_text(angle=45, hjust=1)) +
    labs(y="Proportion of papers in predatory journals", x="Year")
```


## Countries

```{r}
countries <- fread(here("data", "countries.csv"), header=FALSE)
authors2 <- left_join(authors, countries, by=c("country"="V1"))
authors2$country <- authors2$V2

authors2$country[authors2$country == "USA"] <- "United States"
authors2$country[authors2$country == "The Netherlands"] <- "Netherlands"

authors2 <- authors2 %>% mutate(country2 = case_when(
    country == "United Kingdom" ~ "UK",
    country == "United States" ~ "USA",
    country == "China" ~ "China",
    # country == "Sweden" ~ "Sweden",
    # country == "Germany" ~ "Germany",
    # country == "Australia" ~ "Australia",
    # country == "Canada" ~ "Canada",
    # country == "The Netherlands" ~ "The Netherlands",
    # country == "Denmark" ~ "Denmark",
    # country == "South Korea" ~ "South Korea",
    TRUE ~ "All other countries"
))

table(authors2$country2)

temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country2, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp_all <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country, year=year(pub_date)) %>%
    summarise(n=n())


temp %>%
    ggplot(., aes(x=year, y=n, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   scale_y_log10() +
   xlim(2005,2023) +
   theme(legend.position="none")
```

Plot understanding exponential growth

```{r}
temp %>%
    ggplot(., aes(x=year, y=n, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none") +
   labs(y="Number of papers", x="Year")
ggsave("country.pdf", width=8, height=4)
```

## Paper mills

```{r}
paper_mill <- tibble(perc=c(0.92, 0.02, 0, 0.06), country2=c("China", "USA", "UK", "All other countries"))
temp <- left_join(temp, paper_mill, by="country2")
temp$n_adj <- temp$n * (1 - temp$perc)
data_ends <- filter(temp, year == "2023")
temp %>%
    ggplot(., aes(x=year, y=n_adj, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n_adj, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none") +
   labs(y="Relative number of papers adjusted for paper mills", x="Year")

```

Retraction watch paper mill papers

```{r}
format_date <- function(x) {
    do.call(rbind, strsplit(x, " "))[,1] %>% gsub("/", "-", .) %>% as.Date(., format="%m-%d-%Y") %>% lubridate::year()
}

format_country <- function(x) {
    case_when(grepl("China", x) ~ "China", grepl("United States", x) ~ "USA", grepl("United Kingdom", x) ~ "UK", TRUE ~ "All other countries")
}

rw <- read.csv("~/Downloads/retraction_watch.csv")

# split the Country column by ";" and duplicate the row for every country
dim(rw)
rw <- rw %>% tidyr::separate_rows(Country, sep=";")

table(rw$Country)

pm <- paper_milly <- rw %>% filter(grepl("paper mill", Reason, ignore.case=TRUE)) %>%
    mutate(year=format_date(OriginalPaperDate), country2 = format_country(Country)) %>%
    group_by(year, country=Country) %>% summarise(nret=n())

left_join(temp_all, pm) %>%
    mutate(nret = ifelse(is.na(nret), 0, nret)) %>%
    filter(year < 2023) %>%
    ggplot(., aes(x=nret, y=n, colour=year, group=country)) + geom_point() + geom_line(aes(group=country))

left_join(temp_all, pm) %>%
    mutate(nret = ifelse(is.na(nret), 0, nret)) %>%
    filter(country == "China" & year < 2023) %>%
    ggplot(., aes(x=nret, y=n, colour=year)) + geom_point() + geom_line()
```


```{r}
paper_milly <- rw %>% filter(grepl("paper mill", Reason, ignore.case=TRUE)) %>%
    mutate(year=format_date(OriginalPaperDate), country2 = format_country(Country)) %>% 
    group_by(year, country2) %>% summarise(nret=n())

paper_mill_y <- group_by(paper_milly, year) %>% summarise(nret_all=sum(nret))
paper_milly <- left_join(paper_milly, paper_mill_y, by="year") %>% mutate(percrety=nret/nret_all)
ggplot(paper_milly, aes(x=year, y=nret, colour=country2)) + geom_line() + geom_point() + theme(legend.position="bottom") + labs(y="Proportion of papers in paper mills", x="Year") + scale_colour_brewer(type="qual") + xlim(2015,2022)

temp <- left_join(temp, paper_milly, by=c("year"="year", "country2"="country2"))
temp$percrety[is.na(temp$percrety)] <- 0

temp$n_adjy <- temp$n * (1 - temp$percrety)
data_ends <- filter(temp, year == "2023")
temp %>%
    ggplot(., aes(x=year, y=n_adj, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n_adj, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none", ) +
   labs(y="Relative number of papers adjusted for paper mills", x="Year")

temp %>%
    ggplot(., aes(x=year, y=n_adjy, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n_adjy, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none") +
   labs(y="Relative number of papers adjusted for paper mills", x="Year")
```

```{r}
temp %>%
    group_by(year) %>%
    summarise(n=sum(n), n_adjy=sum(n_adjy)) %>%
    tidyr::pivot_longer(cols=c(n, n_adjy), names_to="type", values_to="value") %>%
    ggplot(., aes(x=year, y=value)) + 
    # geom_smooth(se=FALSE) + 
    geom_line(aes(colour=type)) +
   xlim(2005,2023) +
   labs(y="Relative number of papers adjusted for paper mills", x="Year")

```



## China universities

```{r}
c211 <- readLines(here("data", "211_universities.txt"))
table(c211 %in% authors2$institution)

inst <- subset(authors2, !duplicated(institution), institution) %>% mutate(key1=1:n())
c211 <- tibble(c211=c211, key2=1:length(c211))

c985 <- readLines(here("data", "985_universities.txt"))
table(c985 %in% authors2$institution)

c985 <- tibble(c985=c985, key2=1:length(c985))

ctemp_211 <- merge_plus(data1 = inst, data2 = c211, by.x="institution", by.y="c211", match_type="fuzzy", unique_key_1="key1", unique_key_2="key2")
authors2$c211 <- authors2$institution %in% ctemp_211$matches$institution

ctemp_985 <- merge_plus(data1 = inst, data2 = c985, by.x="institution", by.y="c985", match_type="fuzzy", unique_key_1="key1", unique_key_2="key2")
authors2$c985 <- authors2$institution %in% ctemp_985$matches$institution
table(authors2$country == "China", authors2$c211)
table(authors2$country == "China", authors2$c985)
```

```{r}
authors2$country3 <- authors2$country2
authors2$country3[authors2$country3 == "China" & !authors2$c211] <- "China (other)"
authors2$country3[authors2$country3 == "China" & authors2$c211] <- "China (211)"

authors2$country4 <- authors2$country2
authors2$country4[authors2$country4 == "China" & !authors2$c985] <- "China (other)"
authors2$country4[authors2$country4 == "China" & authors2$c985] <- "China (985)"

table(authors2$country3)
table(authors2$country4)
```


```{r}
temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country3, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp %>%
    ggplot(., aes(x=year, y=n, colour=country3)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country3)) +
    geom_text_repel(
        aes(label = country3), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")
```


```{r}
temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country4, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp %>%
    ggplot(., aes(x=year, y=n, colour=country4)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country4)) +
    geom_text_repel(
        aes(label = country4), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")
```

## Understanding the growth in China

Count abstracts based on whether the affiliation is a hospital based university

```{r}
authors2 %>% mutate(hospital = grepl("medical", institution, ignore.case=TRUE) | grepl("hospital", institution, ignore.case=TRUE)) %>%
  group_by(country4, hospital) %>% count()
```

```{r}
authors2 %>% mutate(hospital = grepl("medical", institution, ignore.case=TRUE) | grepl("hospital", institution, ignore.case=TRUE)) %>%
  group_by(country2, hospital) %>% count()
```


Which medical universities have the most abstracts?

```{r}
authors %>% mutate(hospital = grepl("medical", institution, ignore.case=TRUE) | grepl("hospital", institution, ignore.case=TRUE)) %>% filter(hospital, country == "China") %>% group_by(institution) %>% count() %>% arrange(desc(n))
```

```{r}
authors2$country5 <- authors2$country2
authors2 <- authors2 %>% mutate(hospital = grepl("medical", institution, ignore.case=TRUE) | grepl("hospital", institution, ignore.case=TRUE))
authors2$country5[authors2$country2 == "China" & authors2$hospital] <- "China (medical)"

temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country5, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp %>%
    ggplot(., aes(x=year, y=n, colour=country5)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country5)) +
    geom_text_repel(
        aes(label = country5), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")
```

