---
title: Analysis for MR editorial for EJE
author: Gibran Hemani
---


```{r}
library(dplyr)
library(readxl)
library(here)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(janitor)
```


## EJE submissions

```{r}
eje <- read_xlsx(here("data", "2015_2024_Submissions[80].xlsx"), n_max=5) %>% pivot_longer(!Year)
names(eje) <- c("type", "year", "count")
# eje <- bind_rows(eje, eje %>% group_by(year) %>% summarise(count = count[2]-count[1]) %>% mutate(type="Submissions All other countries"))
str(eje)
```


```{r}
eje <- eje %>% filter(year != "2024*", type != "Submissions Total") %>% 
    mutate(type = gsub("Submissions ", "", type)) %>% as.data.frame()

eje_e <- subset(eje, year == "2024")

ggplot(eje, aes(x=year, y=count, fill=type, group=type, colour=type)) +
  geom_line() +
    geom_point(data=eje_e, aes(x=year, y=count)) +
    geom_text_repel(
        aes(label = type), data = eje_e
    ) +
  labs(y="Submissions received by EJE annually") +
  theme(legend.position = "none") +
  expand_limits(y = 0)
```


## EJE MR papers

```{r}
a <- read_xlsx(here("data/Mendelian Randomisation Submissions_2015_24.xlsx"))
a <- clean_names(a)
a$date <- lubridate::mdy(a$initial_date_submitted)
str(a)

a1 <- read_xlsx(here("data/Mendelian Randomisation Submissions_2024.xlsx"))
a1 <- clean_names(a1)
a1$date <- lubridate::mdy(a1$initial_date_submitted)
str(a1)

a <- bind_rows(a, a1) %>% filter(!duplicated(manuscript_number))
dim(a)


table(a$country)
a$type <- ifelse(a$country == "CHINA", "China", "All other countries")

a$year <- lubridate::year(a$date)
a2 <- a %>% group_by(year, type) %>%
  summarise(count=n())


eje_e2 <- subset(a2, year == "2023")

ggplot(a2 %>% filter(year != 2024), aes(x=year, y=count, fill=type, group=type, colour=type)) +
  geom_line() +
    geom_point(data=eje_e2, aes(x=year, y=count)) +
    geom_text_repel(
        aes(label = type), data = eje_e2
    ) +
  labs(y="MR Submissions received by EJE annually") +
  theme(legend.position = "none") +
  expand_limits(y = 0)
```


```{r}
eje$year <- as.numeric(eje$year)
eje_all <- inner_join(eje, a2, by=c("year", "type"), suffix=c("_all", "_mr"))
eje_all$count_other <- eje_all$count_all - eje_all$count_mr

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  ggplot(aes(x=year, y=value, group=type, colour=name)) +
  geom_point() +
  geom_line(aes(group=paste(type, name), linetype=type)) +
  labs(y="Submissions received by EJE annually")

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  filter(name != "count_all") %>% 
  mutate(name = case_when(name == "count_all" ~ "All", name == "count_mr" ~ "MR papers", name == "count_other" ~ "Other papers")) %>%
  ggplot(aes(x=year, y=value, group=type, fill=name)) +
  geom_bar(aes(fill=name, group=type), stat="identity", position="stack") +
  facet_grid( ~ type) +
  labs(x="Year", y="Submissions received by EJE annually", fill="Submission type")
```

Ratios

```{r}
eje_all

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  group_by(name) %>%
  do({
    china <- subset(., type == "China")
    other <- subset(., type == "All other countries")
    a <- inner_join(china, other, by="year")
    a$prop <- a$value.x / (a$value.y + a$value.x)
    a
  }) %>%
  mutate(name = case_when(name == "count_all" ~ "All", name == "count_mr" ~ "MR", name == "count_other" ~ "Other")) %>%
  ggplot(aes(x=year, y=prop, colour=name)) +
  geom_line() +
  scale_colour_brewer(type="qual") +
  labs(x="Year", y="Proportion of submissions from China", colour="Paper type")

```


## Add UK and USA

```{r}
table(a$country)
a$type2 <- "All other countries"
a$type2[a$country == "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND"] <- "UK"
a$type2[a$country == "UNITED STATES OF AMERICA"] <- "USA"
a$type2[a$country == "CHINA"] <- "China"

a2 <- a %>% group_by(year, type=type2) %>%
  summarise(count=n())
all_possible <- expand.grid(year=2015:2024, type=c("China", "UK", "USA", "All other countries"), count=0)
code <- paste(all_possible$year, all_possible$type)
all_possible <- subset(all_possible, ! code %in% paste(a2$year, a2$type))
a2 <- bind_rows(a2, all_possible)

ggplot(a2, aes(x=year, y=count, fill=type, group=type, colour=type)) +
  geom_line() +
    # geom_point(data=eje_e2, aes(x=year, y=count)) +
    # geom_text_repel(
    #     aes(label = type), data = eje_e2
    # ) +
  labs(y="MR Submissions received by EJE annually") +
  # theme(legend.position = "none") +
  expand_limits(y = 0) +
  scale_colour_brewer(type="qual")
```


```{r}
eje$year <- as.numeric(eje$year)
eje_all <- full_join(eje, a2, by=c("year", "type"), suffix=c("_all", "_mr"))
eje_all$count_other <- eje_all$count_all - eje_all$count_mr

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  ggplot(aes(x=year, y=value, group=type, colour=name)) +
  geom_line(aes(group=paste(type, name), linetype=type)) +
  labs(y="Submissions received by EJE annually")

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  filter(name != "count_all") %>% 
  mutate(name = case_when(name == "count_all" ~ "All", name == "count_mr" ~ "MR papers", name == "count_other" ~ "Other papers")) %>%
  ggplot(aes(x=as.factor(year), y=value, group=type, fill=name)) +
  geom_bar(aes(fill=name, group=type), stat="identity", position="stack") +
  facet_grid( ~ type) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, size=8), legend.position=c(0.88,0.78), axis.text.y=element_blank()) +
  labs(x="Year", y="Annual submissions to EJE by country", fill="Submission type") +
  scale_fill_manual(values=gg_color_hue(2), guide=guide_legend(reverse=TRUE))
ggsave("docs/fig1c.pdf", width=7, height=3.5)
```


```{r}
tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  filter(name != "count_all") %>% 
  group_by(year, name) %>%
  summarise(value=sum(value)) %>%
  mutate(name = case_when(name == "count_mr" ~ "MR papers", name == "count_other" ~ "Other papers")) %>%
  ggplot(aes(x=as.factor(year), y=value, fill=factor(name, levels=c("MR papers", "Other papers") %>% rev))) +
  geom_bar(stat="identity", position="stack") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, size=8), legend.position="none", axis.text.y=element_blank()) +
  labs(x="Year", y="Total annual submissions to EJE", fill="Submission type") +
  scale_fill_manual(values=gg_color_hue(2) %>% rev, guide=guide_legend(reverse=TRUE))
ggsave("docs/fig1b.pdf", width=7, height=3.5)
```

## Growth rates

```{r}
calculate_exp_growth <- function(time, counts) {
    # Fit exponential model by taking log of counts
    # N(t) = N0 * e^(rt) becomes log(N(t)) = log(N0) + rt
    counts <- counts + 1
    model <- summary(lm(log(counts) ~ time))

    # Extract growth coefficient (r)
    r <- model$coefficients[2,1]
    r_se <- model$coefficients[2,2]

    # Calculate R-squared to assess fit
    r_squared <- model$r.squared

    # Calculate doubling time
    doubling_time <- log(2)/r

    rdist <- rnorm(1000, r, r_se)
    doubling_time_se <- log(2) * r_se / r^2
    doubling_time_se_emp <- sd(log(2) / rdist)



    # Return results
    return(list(
        growth_coefficient = r,
        growth_coefficient_se = r_se,
        r_squared = r_squared,
        doubling_time = doubling_time,
        doubling_time_se = doubling_time_se,
        doubling_time_se_emp = doubling_time_se_emp,
        initial_value = exp(coef(model)[1])
    ) %>% as_tibble())
}

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  filter(name != "count_all") %>%
  mutate(name = case_when(name == "count_all" ~ "All", name == "count_mr" ~ "MR papers", name == "count_other" ~ "Other papers")) %>%
  group_by(name, type=type) %>%
  do({
    calculate_exp_growth(.$year, .$value)
  }) %>% as.data.frame
```



## Adjusting for estimated paper mill fraction

Suppose that some fraction of all papers come from paper mills. 



```{r, eval=FALSE}

paper_mill_fraction <- tibble(
  
)

tidyr::pivot_longer(eje_all, c(count_all, count_mr, count_other)) %>%
  filter(name != "count_all") %>% 
  mutate(name = case_when(name == "count_all" ~ "All", name == "count_mr" ~ "MR papers", name == "count_other" ~ "Other papers")) %>%
  group_by(name, type) %>%
  do({
    calculate_exp_growth(.$year, .$value)
  }) %>% as.data.frame

```



## Nature Index



```{r}
ni <- lapply(2016:2024, \(y) {
  a <- read.csv(here("data", "nature_index", paste0(y, "-research-leading-countries.csv"))) %>% clean_names()
  i <- which(names(a) == paste0("share_", y-1))
  names(a)[i] <- "share"
  i <- which(names(a) == paste0("count_", y-1))
  names(a)[i] <- "count"
  a <- a %>% select(position, country=country_territory, share, count) %>% mutate(year=y)
}) %>% bind_rows()

ni$country2 <- ni$country
ni$country2[! ni$country2 %in% c("United States of America (USA)", "United Kingdom (UK)", "China")] <- "All other countries"
ni <- ni %>% group_by(country2, year)  %>% summarise(share = sum(share), count=sum(count), position=mean(position))

ggplot(ni, aes(x=year, y=share, group=country2, colour=country2)) +
  geom_line() +
  geom_point() +
  labs(y="Nature Index share of top 10 countries") +
  expand_limits(y = 0) +
  scale_colour_brewer(type="qual")

ggplot(ni, aes(x=year, y=count, group=country2, colour=country2)) +
  geom_line() +
  geom_point() +
  labs(y="Nature Index count of top 10 countries") +
  expand_limits(y = 0) +
  scale_colour_brewer(type="qual")
```


