---
title: "Initial analysis of OpenAI abstract summaries"
author: "Gibran Hemani"
date: "2024-05-25"
---

```{r}
library(here)
library(dplyr)
library(jsonlite)
library(lubridate)
library(ggplot2)
library(forcats)
library(ggrepel)
```

```{r}
a <- jsonlite::read_json(here("data", "pubmed.json")) %>%
    lapply(., function(x) {
        x <- as_tibble(x)
        x
    }) %>% 
    bind_rows() %>%
    mutate(
        pub_date=ymd(pub_date),
        week=ceiling_date(pub_date, "weeks"),
    )

a1 <- jsonlite::read_json(here("data", "pubmed_new.json")) %>%
    lapply(., function(x) {
        x <- as_tibble(x)
        x
    }) %>% 
    bind_rows() %>%
    mutate(
        pub_date=ymd(pub_date),
        week=ceiling_date(pub_date, "weeks"),
    )

a <- bind_rows(a, a1)
dim(a)
length(unique(a$pmid))
```

```{r}
parse_res <- function(x) {
    o <- list()
    if(length(x$exposures) > 0) {
        if(!"id" %in% names(x$exposures)) {
            o$exposure <- tibble(
                pmid=x$pmid,
                what = "exposure",
                trait = sapply(x$exposures, function(y) { if("trait" %in% names(y)) y$trait else NA_character_}),
                category = sapply(x$exposures, function(y) {
                    if("category" %in% names(y)) {y$category } 
                    else if("group" %in% names(y)) {y$group} 
                    else {NA_character_}
                })
            )
        } else {
            o$exposure <- tibble(
                pmid=x$pmid,
                what = "exposure",
                trait = x$exposures$trait,
                category = x$exposures$category
            )
        }
    } else {
        o$exposure <- tibble(
            pmid=x$pmid,
            what = "exposure",
            trait = "NONE",
            category = NA_character_
        )
    }
    if(length(x$outcomes) > 0) {
        if(!"id" %in% names(x$outcomes)) {
            o$outcome <- tibble(
                pmid=x$pmid,
                what = "outcome",
                trait = sapply(x$outcomes, function(y) { if("trait" %in% names(y)) y$trait else NA_character_}),
                category = sapply(x$outcomes, function(y) {
                    if("category" %in% names(y)) {y$category } 
                    else if("group" %in% names(y)) {y$group} 
                    else {NA_character_}
                })
            )
        } else {
            o$outcome <- tibble(
                pmid=x$pmid,
                what = "outcome",
                trait = x$outcomes$trait,
                category = x$outcomes$category
            )
        }
    } else {
        o$outcome <- tibble(
            pmid=x$pmid,
            what = "outcome",
            trait = "NONE",
            category = NA_character_
        )
    }
    o <- bind_rows(o)
    if("methods" %in% names(x)) {
        m <- tibble(
            pmid=x$pmid,
            methods = unlist(x$methods)
        )
    } else {
        m <- tibble()    
    }
    if("results" %in% names(x)) {
        r <- tibble(
            pmid=x$pmid,
            null = x$results$null,
            nonnull = x$results$`non-null`
        )
    } else {
        r <- tibble()    
    }
    return(list(o=o, m=m, r=r))
}

b <- jsonlite::read_json(here("data", "pubmed_abstracts3.json")) 
b1 <- b %>%
{
    lapply(., function(x) {
        tryCatch({
            parse_res(x)
        }, error=function(e) {
            return(NULL)
        })
    })
}

traits <- lapply(b1, function(x) x$o) %>% bind_rows()
meth <- lapply(b1, function(x) x$m) %>% bind_rows()
nulls <- lapply(b1, function(x) x$r) %>% bind_rows()
```

```{r}
dat <- inner_join(a, traits, by="pmid")

str(dat)
length(unique(dat$pmid))
```

```{r}
permitted_categories <- c("molecular","socioeconomic","environmental","behavioural","anthropometric","clinical measures","infectious disease","neoplasm","disease of the blood and blood-forming organs","metabolic disease","mental disorder","disease of the nervous system","disease of the eye and adnexa","disease of the ear and mastoid process","disease of the circulatory system","disease of the digestive system","disease of the skin and subcutaneous tissue","disease of the musculoskeletal system and connective tissue","disease of the genitourinary system")
```

```{r}
permitted_methods <- c(
    "two-sample mendelian randomization",
    "multivariable mendelian randomization",
    "colocalization",
    "network mendelian randomization",
    "triangulation",
    "reverse mendelian randomization",
    "one-sample mendelian randomization",
    "negative controls",
    "sensitivity analysis",
    "non-linear mendelian randomization",
    "bi-directional mendelian randomization",
    "within-family mendelian randomization"
)

meth$methods <- tolower(meth$methods)
meth1 <- subset(meth, methods %in% permitted_methods)
table(tolower(meth1$methods))
meth2 <- subset(meth, !methods %in% permitted_methods)
sum(grepl("^mendelian randomization$", meth2$methods), ignore.case=TRUE)
sum(grepl("^mendelian randomisation$", meth2$methods), ignore.case=TRUE)
table(table(tolower(meth2$methods)))

meth2 %>% group_by(methods) %>% summarise(n=n()) %>% arrange(desc(n)) %>% head(100) %>% as.data.frame

# "heritability", "heritability analysis",
# "summary", "two-sample mendelian randomization",
# "^mendelian randomization$", "one-sample mendelian randomization",
# "multivariate mendelian randomization", "multivariable mendelian randomization",
# "bidirectional mendelian randomization", "bi-directional mendelian randomization",
```

```{r}
table(nulls$null)
table(nulls$nonnull)
arrange(nulls, desc(null))
```


```{r}
temp1 <- dat %>%
    group_by(pmid, what) %>%
    filter(!duplicated(category)) %>%
    ungroup() %>%
    mutate(category = tolower(category)) %>%
    filter(category %in% permitted_categories)

dim(temp1)
subset(temp1, category == "anthropometric")$trait %>% table()

temp2 <- filter(dat, !duplicated(pmid)) %>%
    group_by(week) %>%
    summarise(npubs=n())

temp3 <- temp1 %>%
    group_by(what, week, category) %>%
    summarise(n=n()) %>%
    inner_join(., temp2, by="week") %>%
    mutate(prop=n/npubs)
```

```{r}
ggplot(temp3, aes(x=week, y=n, colour=what)) + geom_smooth() + facet_wrap(~category, scales="free_y")
```

```{r}
temp1 %>% group_by(what, category) %>% summarise(n=n()) %>% arrange(desc(n)) %>%
ggplot(., aes(x=reorder(category, n), y=n, fill=what)) + geom_bar(stat="identity") + coord_flip() + theme(legend.position="bottom")
```


```{r}
nonecount <- group_by(traits, pmid) %>%
    summarise(NONE = sum(trait == "NONE")) %>%
    inner_join(., a %>% select(pmid, pub_date), by="pmid")
table(nonecount$NONE)
```

```{r}
summary(lm(NONE ~ I(today() - pub_date), data=nonecount))
```

```{r, eval=FALSE, echo=FALSE}
missing_pmids <- a$pmid[!a$pmid %in% b1$pmid]

length(missing_pmids)
subset(a, pmid %in% missing_pmids)$pub_date

write.table(missing_pmids, here("data", "missing_pmids.txt"), row.names=FALSE, col.names=FALSE, qu=FALSE)
```


```{r}
authors <- jsonlite::read_json(here("data", "pubmed_authors.json")) %>%
    lapply(., \(x) {
        tibble(pmid=x$pmid, country=unlist(x$country), institution=unlist(x$institution))
    }) %>%
    bind_rows()
group_by(authors, country) %>% summarise(n=n()) %>% arrange(desc(n)) %>% head(100)
```



```{r}
abstracts <- a
traits <- traits %>%
    mutate(category = tolower(category), permitted_category = category %in% permitted_categories)
str(traits)
str(abstracts)
meth1
meth2
nulls


save(traits, abstracts, authors, nulls, meth1, meth2, file=here("data", "results.RData"))
```


##

```{r}
load(here("data", "results.RData"))
```


```{r}
head(meth1)
head(traits)
temp <- inner_join(traits, abstracts, by="pmid") %>%
    filter(permitted_category & !duplicated(paste(pmid, category))) %>%
    group_by(category, year=year(pub_date)) %>%
    summarise(n=n()) %>%
    group_by(year) %>%
    mutate(prop=n/sum(n))

p <- temp %>%
ggplot(., aes(x=year, y=prop, colour=category)) + geom_line() + theme(legend.position="bottom") + xlim(2005,2024)

#ggplotly(p)
```


```{r}
temp <- inner_join(meth1, abstracts, by="pmid") %>%
    filter(!duplicated(paste(pmid, methods))) %>%
    group_by(methods, year=year(pub_date)) %>%
    summarise(n=n()) %>%
    group_by(year) %>%
    mutate(prop=n/sum(n))

temp
p <- temp %>%
ggplot(., aes(x=year, y=prop, colour=methods)) + geom_line() + theme(legend.position="bottom") + xlim(2005,2024)
p
```


```{r}
temp <- read.table(here("data", "predatory_journals.txt"), sep="\t", header=FALSE)

predj <- tibble(
    journal1 = gsub("\\s*\\([^\\)]+\\)","",as.character(temp$V1)) %>% tolower(),
    key1=1:length(journal1)
)

mrj <- subset(abstracts, !duplicated(journal), select=c(journal)) %>% mutate(key2=1:length(journal), journal=gsub("\\s*\\([^\\)]+\\)","",as.character(journal)) %>% tolower())

library(fedmatch)

temp <- merge_plus(data1 = mrj, data2 = predj, by.x="journal", by.y="journal1", match_type="fuzzy", unique_key_1="key2", unique_key_2="key1")

head(temp)
dim(temp$matches)



mrj$predatory <- mrj$journal %in% temp$matches$journal
table(mrj$predatory)
abstracts$journal <- gsub("\\s*\\([^\\)]+\\)","",as.character(abstracts$journal)) %>% tolower()
abstracts$predatory <- abstracts$journal %in% temp$matches$journal

group_by(abstracts, year=year(pub_date)) %>%
    summarise(n=n(), npred=sum(predatory)) %>%
    mutate(prop=npred/n, sem = sqrt(npred * (n-npred)/n^3), lci = pmax(0, prop - (1.96 * sem)), uci = pmin(prop + (1.96 * sem), 1)) %>%
    ggplot(., aes(x=year, y=prop, ymin=lci, ymax=uci)) + geom_line() + geom_ribbon(alpha=0.2) + theme(legend.position="bottom") + xlim(2005,2024) +
    geom_text(aes(label=npred), vjust=-1) +
    scale_x_continuous(breaks=seq(2005,2024,1), limits=c(2005, 2024)) +
    theme(axis.text.x=element_text(angle=45, hjust=1)) +
    labs(y="Proportion of papers in predatory journals", x="Year")
```



```{r}
unique(authors$country) %>% cat(sep="\n")

```



## Countries

```{r}
library(data.table)
countries <- fread(here("data", "countries.csv"), header=FALSE)
authors2 <- left_join(authors, countries, by=c("country"="V1"))
authors2$country <- authors2$V2

authors2 <- authors2 %>% mutate(country2 = case_when(
    country == "United Kingdom" ~ "UK",
    country == "USA" ~ "USA",
    country == "China" ~ "China",
    # country == "Sweden" ~ "Sweden",
    # country == "Germany" ~ "Germany",
    # country == "Australia" ~ "Australia",
    # country == "Canada" ~ "Canada",
    # country == "The Netherlands" ~ "The Netherlands",
    # country == "Denmark" ~ "Denmark",
    # country == "South Korea" ~ "South Korea",
    TRUE ~ "All other countries"
))

table(authors2$country2)


temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country2, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp %>%
    ggplot(., aes(x=year, y=n, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   scale_y_log10() +
   xlim(2005,2023) +
   theme(legend.position="none")
```

Plot showing the exponential growth in China

```{r}
temp %>%
    ggplot(., aes(x=year, y=n, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")
```

```{r}
temp %>%
    filter(country2 != "China") %>%
    ggplot(., aes(x=year, y=n, colour=country2)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends %>% filter(country2 != "China"), aes(x=year, y=n, colour=country2)) +
    geom_text_repel(
        aes(label = country2), data = data_ends%>% filter(country2 != "China")
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")

```

## China universities

```{r}
c211 <- readLines(here("data", "211_universities.txt"))
table(c211 %in% authors2$institution)

inst <- subset(authors2, !duplicated(institution), institution) %>% mutate(key1=1:n())
c211 <- tibble(c211=c211, key2=1:length(c211))

c985 <- readLines(here("data", "985_universities.txt"))
table(c985 %in% authors2$institution)

c985 <- tibble(c985=c985, key2=1:length(c985))

ctemp_211 <- merge_plus(data1 = inst, data2 = c211, by.x="institution", by.y="c211", match_type="fuzzy", unique_key_1="key1", unique_key_2="key2")
authors2$c211 <- authors2$institution %in% ctemp_211$matches$institution

ctemp_985 <- merge_plus(data1 = inst, data2 = c985, by.x="institution", by.y="c985", match_type="fuzzy", unique_key_1="key1", unique_key_2="key2")
authors2$c985 <- authors2$institution %in% ctemp_985$matches$institution

table(authors2$country == "China", authors2$c211)
table(authors2$country == "China", authors2$c985)
authors2$country3 <- authors2$country2
authors2$country3[authors2$country3 == "China" & !authors2$c211] <- "China (other)"
authors2$country3[authors2$country3 == "China" & authors2$c211] <- "China (211)"

authors2$country4 <- authors2$country2
authors2$country4[authors2$country4 == "China" & !authors2$c985] <- "China (other)"
authors2$country4[authors2$country4 == "China" & authors2$c985] <- "China (985)"

table(authors2$country3)
table(authors2$country4)
```


```{r}
temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country3, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp %>%
    ggplot(., aes(x=year, y=n, colour=country3)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country3)) +
    geom_text_repel(
        aes(label = country3), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")
```


```{r}
temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid") %>%
    group_by(country4, year=year(pub_date)) %>%
    summarise(n=n()) 
data_ends <- filter(temp, year == "2023")

temp %>%
    ggplot(., aes(x=year, y=n, colour=country4)) + 
    # geom_smooth(se=FALSE) + 
    geom_line() +
    geom_point(data=data_ends, aes(x=year, y=n, colour=country4)) +
    geom_text_repel(
        aes(label = country4), data = data_ends
    ) +
   xlim(2005,2023) +
   theme(legend.position="none")
```


## Exponential growth?

```{r}
ex <- rexp(10000, rate = 1.85) # generate some exponential distribution
control <- abs(rnorm(10000)) # generate some other distribution

# estimate the parameters
fit1 <- fitdistr(ex, "exponential") 
fit2 <- fitdistr(control, "exponential")

# goodness of fit test
ks.test(ex, "pexp", fit1$estimate) # p-value > 0.05 -> distribution not refused
ks.test(control, "pexp", fit2$estimate) #  significant p-value -> distribution refused

# plot a graph
hist(ex, freq = FALSE, breaks = 100, xlim = c(0, quantile(ex, 0.99)))
x <- ex
curve(dexp(x, rate = fit1$estimate), from = 0, col = "red", add = TRUE)

require(MASS)


temp <- authors2 %>%
    filter(!duplicated(pmid)) %>% inner_join(., subset(abstracts, select=c(pmid, pub_date)), by="pmid")

a <- as.period(ymd(temp$pub_date) - ymd("2003-01-01")) / months(1)
hist(a)


fit1 <- fitdistr(a, "exponential")
o <- ks.test(a, "pexp", fit1$estimate)
o$p.value

plot(temp$)





lapply(unique(authors2$country3), function(x) {
    te <- subset(temp, country3 == x)
    a <- as.period(te$pub_date - min(te$pub_date)) / months(1)
    fit1 <- fitdistr(a, "exponential")
    o <- ks.test(a, "pexp", fit1$estimate)
    tibble(country=x, p=o$p.value, D=o$statistic)
}) %>% bind_rows()


a <- as.period(ymd(temp$pub_date) - ymd("2003-01-01")) / months(1)
hist(a)

fit1 <- fitdistr(a, "exponential")
ks.test(a, "pexp", fit1$estimate)

plot(dexp())

hist(a, breaks=100)
curve(dexp(x, rate = fit1$estimate), from = 0, col = "red", add = TRUE)



```



## Methods

```{r}
meth1

group_by(meth1, pmid) %>%
summarise(n=n()) %>%
inner_join(., abstracts %>% select(pmid, pub_date), by="pmid") %>%
mutate(year=year(pub_date)) %>%
filter(year <= 2024) %>%
ggplot(., aes(x=year, y=n)) + geom_violin(aes(as.factor(year))) +
labs(y="Number of methods mentioned in abstract")
```


```{r}
temp <- meth1 %>%
inner_join(., abstracts %>% select(pmid, pub_date), by="pmid") %>%
mutate(year=year(pub_date)) %>%
group_by(methods, year) %>%
summarise(n=n()) 

data_ends <- filter(temp, year == 2023)

ggplot(temp, aes(x=year, y=n, colour=methods)) + geom_line() + theme(legend.position="none") + xlim(2005,2023) +
scale_y_log10() + 
    geom_text_repel(
        aes(label = methods), data = data_ends
    ) +
    labs(y="Number of papers mentioning method", x="Year")
```



## Impact factor

```{r}
citescore <- read.csv("~/Downloads/CiteScore 2023.csv")
citescore <- bind_rows(
    select(citescore, issn=Print.ISSN, CiteScore),
    select(citescore, issn=E.ISSN, CiteScore)
) %>% filter(issn != "") %>% filter(!duplicated(issn))

head(citescore)

abstracts$issn <- gsub("-", "", abstracts$journal_issn)
table(unique(abstracts$issn) %in% citescore$Print.ISSN)
table(abstracts$issn %in% citescore$E.ISSN | abstracts$issn %in% citescore$Print.ISSN)

abstracts_cs <- inner_join(abstracts, citescore)
abstracts_cs <- inner_join(abstracts_cs, authors2 %>% select(pmid, country2))
```

```{r}
ggplot(abstracts_cs, aes(x=year(pub_date), y=CiteScore)) + geom_jitter() + geom_smooth() + theme(legend.position="none") + xlim(2003,2023)
```

```{r}
abstracts_cs %>%
filter(year(pub_date) <= 2024) %>%
ggplot(., aes(x=year(pub_date), y=CiteScore)) + geom_boxplot(aes(groups=as.factor(year(pub_date)))) + geom_smooth() + theme(legend.position="none") + geom_smooth(aes(x=year(pub_date))) +
facet_grid(~country2)
```


```{r}
abstracts_cs_meth <- inner_join(abstracts_cs, meth1, by="pmid")

temp <- group_by(abstracts_cs_meth, methods) %>%
    summarise(nmeth=n(), CiteScore=mean(CiteScore))

abstracts_cs_meth %>%
    ggplot(., aes(x=reorder(methods, CiteScore), y=CiteScore)) + geom_boxplot() + theme(legend.position="none") + coord_flip()
```

```{r}
abstracts_cs_meth %>%
    group_by(pmid) %>%
        summarise(nmeth=n(), CiteScore=mean(CiteScore)) %>%
        group_by(nmeth) %>%
        summarise(CiteScore=mean(CiteScore)) %>%
    ggplot(., aes(x=nmeth, y=CiteScore)) + geom_point()
```



